<?php require 'bootstrap.php'; require 'partials.php'; $user=require_active(); $types=['Constitution','Latest Bank Statement','Annual Accounts','Safeguarding Policy']; $descriptions=['Constitution'=>'Your governing document','Latest Bank Statement'=>'Most recent bank statement','Annual Accounts'=>'Most recent annual accounts','Safeguarding Policy'=>'Your safeguarding policy document']; $message='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$type=$_POST['document_type']??'';$note=trim($_POST['note']??'');$docs=load_json('documents.json');$fileName='';
 if(!empty($_FILES['document']['name'])){$ext=strtolower(pathinfo($_FILES['document']['name'],PATHINFO_EXTENSION));if(in_array($ext,$config['allowed_upload_extensions'],true)&&$_FILES['document']['size']<=$config['max_upload_bytes']){$safe=$user['id'].'_'.time().'_'.preg_replace('/[^A-Za-z0-9._-]/','_',basename($_FILES['document']['name']));move_uploaded_file($_FILES['document']['tmp_name'],UPLOAD_DIR.'/'.$safe);$fileName=$safe;}else{$message='Upload a PDF or Word file smaller than 10MB.';}}
 $found=false;foreach($docs as &$d){if($d['user_id']===$user['id']&&$d['type']===$type){if($fileName)$d['file']=$fileName;$d['note']=$note;$d['updated_at']=date('c');$found=true;}}
 if(!$found)$docs[]=['id'=>count($docs)+1,'user_id'=>$user['id'],'type'=>$type,'file'=>$fileName,'note'=>$note,'updated_at'=>date('c')];save_json('documents.json',$docs);$message=$message?:'Document vault updated.';}
$docs=array_filter(load_json('documents.json'),fn($d)=>$d['user_id']===$user['id']);$map=[];foreach($docs as $d)$map[$d['type']]=$d;dashboard_start($user,'vault'); ?>
<div class="workspace-header compact-header"><div><h1>Document Vault</h1><p>Store your essential organisation documents securely.</p></div></div><?php if($message): ?><div class="alert success"><?= e($message) ?></div><?php endif; ?>
<div class="vault-table"><div class="vault-head"><span>Document Type</span><span>Your File</span><span>Upload / Update</span><span>Notes</span></div><?php foreach($types as $type): $doc=$map[$type]??[]; ?><form method="post" enctype="multipart/form-data" class="vault-row visual-vault"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="hidden" name="document_type" value="<?= e($type) ?>"><div class="vault-info"><h2><?= e($type) ?></h2><span><?= e($descriptions[$type]) ?></span></div><div class="current-file"><?php if(!empty($doc['file'])): ?><span class="pdf-icon">▣</span><div><a href="uploads/<?= e($doc['file']) ?>" target="_blank"><?= e($doc['file']) ?></a><small>Uploaded <?= !empty($doc['updated_at'])?(new DateTime($doc['updated_at']))->format('d/m/Y'):'' ?></small></div><?php else: ?><span>No file uploaded</span><?php endif; ?></div><label class="upload-control"><input type="file" name="document" accept=".pdf,.doc,.docx"><span>Choose file<br><small>PDF, DOC or DOCX</small></span></label><div class="vault-note-wrap"><textarea name="note" placeholder="Add notes (optional)"><?= e($doc['note']??'') ?></textarea><button class="save-mini" type="submit" aria-label="Save">Save</button></div></form><?php endforeach; ?></div>
<div class="security-note">✦ All files are stored securely. Only you can access your documents.</div>
<?php dashboard_end(); ?>
